# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1eeef82b6ac24ad2d35e51862ae79a552f56dc7e24c16e71a8d599c1f3f85c2868aab1d1bddff17228a7103d4b8464c5c168c68441ca4fa1b899a760c0439d9

test:
  secret_key_base: 4861fd6688812414ac5a01844e616a4629843a7ffab0c5ebfb351e18b9e81c138d907e283fcbf1f1cb5ce9fee8cf8a50d14ebdad48742c019c85637e6742b1f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
